services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post1234
      POSTGRES_DB: parkqr
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres: